# Add additional packages that are needed for this specific repo that aren't included in your HM config
{ pkgs ? import <nixpkgs> {} }:

let
  # Install specific Terraform package from nixos-config
  terraform = pkgs.callPackage ../../nixos-config/pkgs/terraform/default-arm64.nix {};
  vault = pkgs.callPackage ../../nixos-config/pkgs/vault/default-arm64.nix {}; # Use the specific version of Vault you need
in

pkgs.mkShell {
  buildInputs = [ 
    terraform
    vault
    pkgs.jq
  ];


# Add extra environment variables here.
EXAMPLE = "Example Env Var";
VAULT_ADDR = "http://0.0.0.0:9200";
VAULT_LICENSE = "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JLFKFKMKPKRETAWKXJV2E23KNGRGUGMLKJZCFK6CMKRTTKTTKIF2E4MSZPBHVIZ3XJVVFM2KPIRCTASLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJEZFUR2FO5HEOTLZLJBTC22NNJVXUTCUJUYFU3KVORHGUWLXJZUTC3KNGJITKTRSKZWVSMSSNFNEIZ3JJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SVORGUIZ3UJVKGYVKNKRITMTLKJE3E4VCBOVHGU23YJVCE2NCNKRCTIV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJGFGFIQJUJRKEKNKWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKLF2E2RCJORGWU2CVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJMXITKEJF2E22TIKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZNGQZCXPAYES2LXNFNG26DILIZU22KPNZ2DSZSRHU6S4MZSO5RCWV2VKN3TC5LOKRGDAVDROMZFUVRSI4ZTCWCONRKVO5DLOBLVSU2DLJBG2TSHKRRTGY3XOZWVK52XGNJU453HGFJWMMSWNZLU453XK5CTSK3UPJLE222YGZLHIT2YHBIUCSRRMRAWWY3BGRSFMMBTGM4FA53NKZWGC5SKKA2HASTYJFETSRBWKVDEYVLBKZIGU22XJJ2GGRBWOBQWYNTPJ5TEO3SLGJ5FAS2KKJWUOSCWGNSVU53RIZSSW3ZXNMXXGK2BKRHGQUC2M5JS6S2WLFTS6SZLNRDVA52MG5VEE6CJG5DU6YLLGZKWC2LBJBXWK2ZQKJKG6NZSIRIT2PI";

}